Goodtables Blog
frictionlessdata/fellows pull request #184
Opened 2022-03-23 16:59 UTC by vyelnats

# Overview

Please replace this line with full information about your pull request. Make sure that tests pass before publishing it

2022-04-06 21:07 UTC, lwinfree requested changes
Hi @vyelnats! Let's look at this together -tomorrow- (Friday, not Thursday) when we meet. You'll need to make some edits, but it might be complicated, so we can do it together :-)

2022-04-08 18:09 UTC, vyelnats commented
I just changed the title in here! Is that ok or do I need to re-push completely

2022-04-13 20:05 UTC, lwinfree commented
Hi! This looks good! There is one more thing, which is you need to write the date in YYYY-MM-DD format in the frontmatter, but I'm going to fix that for you this time :-) Great blog post - love the content!

2022-04-13 20:06 UTC, lwinfree approved these changes

2022-04-13 20:06 UTC, merged